name: build

on: [push]

jobs:
  test:
    if: ${{!startsWith(github.ref, 'refs/tags/')}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: task package

  create-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Create GH release
        uses: ncipollo/release-action@v1
        with:
          name: ${{github.ref_name}}
          draft: false
          prerelease: false
          tag: ${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  compile:
    if: startsWith(github.ref, 'refs/tags/')
    needs: create-release
    runs-on: ubuntu-latest
    env:
      ARCHIVE_FILENAME: extraterm-commands-${{github.ref_name}}.zip
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: task package

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARCHIVE_FILENAME }}
          path: ${{ env.ARCHIVE_FILENAME }}

      - name: Upload release binaries
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["${{ env.ARCHIVE_FILENAME }}"]'
