name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: task package

      - name: Create GH release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          gh release create "${{github.ref_name}}" \
            --draft \
            --title="${{github.ref_name}}" \
            --repo="$GITHUB_REPOSITORY" \
            build/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
