name: build

on: [push]

jobs:
  test:
    if: ${{!startsWith(github.ref, 'refs/tags/')}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: task package

  create-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    env:
      ARCHIVE_FILENAME: extraterm-commands-${{github.ref_name}}.zip
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: task package

      - name: Create GH release
        run: gh release create -d -t "${{github.ref_name}}" "${{github.ref_name}}" ${{ env.ARCHIVE_FILENAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
