name: test

on: [push]

jobs:
  build:
    if: ${{!startsWith(github.ref, 'refs/tags/')}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: task package

  create-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Create GH release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          tag_name: ${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  precompile:
    if: startsWith(github.ref, 'refs/tags/')
    needs: create-release
    runs-on: ubuntu-latest
    env:
      ARCHIVE_FILENAME: extraterm-commands-${{github.ref_name}}.zip
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: task package

      - uses: actions/upload-artifact@v1
        with:
          name: ${{ env.ARCHIVE_FILENAME }}
          path: ${{ env.ARCHIVE_FILENAME }}

      - name: Upload release binaries
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["${{ env.ARCHIVE_FILENAME }}"]'
